#!/usr/bin/env python3
"""Install the shared-layer shim into FlowBank's DiverseFlow stage.

DiverseFlow is stage 1 of FlowBank's precompute-and-reuse pipeline: an AFlow-style
search that generates a pool of candidate workflows. FlowBank ships a curated
portfolio and a trained selector, but neither can be reused here -- its splits
overlap our canonical test sets (203 of our 500 MBPP items match by task_id), so
scoring against a portfolio selected on them would leak test data into one of the
methods being ranked. The pipeline has to be re-run on the canonical splits, which
is what this shim makes possible.

Unlike the AFlow shim, no benchmark substitution is needed: DiverseFlow ships
native benchmark classes, operator sets and workspace templates for all five of
our datasets, MMLU-Pro included.

    python shims/diverseflow/install.py [--check]
"""

from __future__ import annotations

import argparse
import ast
import json
import re
import shutil
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import dedent_patch  # noqa: E402
import namespace_patch  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
HERE = Path(__file__).resolve().parent
FLOWBANK = ROOT / "third_party" / "flowbank"
REPO = FLOWBANK / "DiverseFlow"
DATA = ROOT / "shared" / "data"

MARKER = "# --- shared-layer shim (agent_wf_v2) ---"

# shared key -> (eval split file, search split file, native dataset to copy
# question_type / operators / workspace from)
DATASETS = {
    "SHARED_MATH": ("math.jsonl", "math_search.jsonl", "MATH"),
    # AMC adopted verbatim from FlowBank's shipped split for comparability with
    # its published numbers (2026-08-24): search on its 165-item validate pool,
    # evaluate on its 655-item test set.
    "SHARED_AMC": ("amc.jsonl", "amc_search.jsonl", "AMC"),
    "SHARED_MBPP": ("mbpp.jsonl", "mbpp_search.jsonl", "MBPP"),
    "SHARED_DROP": ("drop.jsonl", "drop_search.jsonl", "DROP"),
    "SHARED_MMLUPRO": ("mmlu_pro.jsonl", "mmlu_pro_search.jsonl", "MMLU_Pro"),
}

# Files this installer rewrites. Every one must still compile: a marker-string
# check cannot tell a working patch from one that wrote a SyntaxError, and that
# failure surfaces much later as an unrelated-looking import error.
PATCHED_SOURCES = ("run.py", "run_test.py", "scripts/evaluator.py",
                   "benchmarks/shared_benchmarks.py")

# Any `workspace<suffix>.<DATASET>.workflows.` module prefix, whatever package
# name or dataset the author's copy happened to reference.
WORKSPACE_IMPORT = re.compile(r"\bworkspace[A-Za-z0-9_]*\.[A-Za-z0-9_]+\.workflows\.")

problems: list[str] = []


def report(ok: bool, message: str) -> None:
    print(f"  [{'ok' if ok else 'FAIL'}] {message}")
    if not ok:
        problems.append(message)


CONFIG_TEMPLATE = """# Generated by shims/diverseflow/install.py -- do not hand-edit.
#
# DiverseFlow ships only config.example.yaml, so without this file the model
# lookup finds nothing and every round dies before it starts. Optimizer and
# executor are the same local Qwen3-8B behind the experiment proxy, which pins
# temperature to 0, disables thinking, caps max_tokens to the protocol budget and
# records per-namespace token accounting.
models:
  qwen3-8b:
    api_type: "openai"
    model: "qwen3-8b"
    base_url: "http://127.0.0.1:18080/train/flowbank/v1"
    api_key: "local"
    temperature: 0
"""


def write_config() -> None:
    config_dir = REPO / "config"
    config_dir.mkdir(parents=True, exist_ok=True)
    # The example header documents `cp config/config.example.yaml config/config.yaml`,
    # so config.yaml is the name the loader looks for. config2.yaml is written too
    # because the AFlow lineage this fork comes from used that name and parts of
    # the tree still reference it.
    for name in ("config.yaml", "config2.yaml"):
        (config_dir / name).write_text(CONFIG_TEMPLATE, encoding="utf-8")
    report("qwen3-8b" in (config_dir / "config.yaml").read_text(encoding="utf-8"),
           "config -> DiverseFlow/config/{config,config2}.yaml")


def install_files() -> None:
    target = REPO / "benchmarks" / "shared_benchmarks.py"
    shutil.copyfile(HERE / "shared_benchmarks.py", target)
    report(target.exists(), f"{target.relative_to(ROOT)}")


def _native_config(text: str, dataset: str) -> tuple[str, list[str]] | None:
    """Read question_type and operators from the author's own entry.

    Copied rather than hardcoded so the shared datasets keep exactly the operator
    sets the authors chose for the same benchmark -- inventing a set here would
    silently change what the search is allowed to explore.
    """
    pattern = re.compile(
        r'"' + re.escape(dataset) + r'": ExperimentConfig\(\s*'
        r'dataset="[^"]*",\s*question_type="(\w+)",\s*operators=(\[[^\]]*\])',
        re.S,
    )
    match = pattern.search(text)
    if not match:
        return None
    return match.group(1), list(ast.literal_eval(match.group(2)))


def patch_run() -> None:
    path = REPO / "run.py"
    text = path.read_text(encoding="utf-8")
    if MARKER in text:
        report(True, "run.py already patched")
        return

    blocks = [f"\n{MARKER}"]
    for key, (_eval_file, _search_file, native) in DATASETS.items():
        native_config = _native_config(text, native)
        if native_config is None:
            report(False, f"{key}: no native {native} config to copy")
            continue
        question_type, operators = native_config
        blocks.append(
            f'EXPERIMENT_CONFIGS["{key}"] = ExperimentConfig(\n'
            f'    dataset="{key}",\n'
            f'    question_type="{question_type}",\n'
            f'    operators={operators!r},\n'
            f")"
        )

    anchor = re.search(r"\n(if __name__ == .__main__.:)", text)
    if not anchor:
        report(False, "run.py main guard not found")
        return
    text = text[: anchor.start()] + "\n" + "\n".join(blocks) + "\n" + text[anchor.start():]
    path.write_text(text, encoding="utf-8")
    report(MARKER in path.read_text(encoding="utf-8"),
           f"run.py patched ({len(blocks) - 1} shared datasets)")


def patch_run_test() -> None:
    """Stage 3 evaluates the selected rounds on test data through run_test.py.

    It has its own copy of the dataset table, so patching run.py alone would leave
    the shared datasets unreachable exactly at the point where the held-out
    numbers are produced.
    """
    path = REPO / "run_test.py"
    if not path.exists():
        report(False, "run_test.py missing")
        return
    text = path.read_text(encoding="utf-8")
    if MARKER in text:
        report(True, "run_test.py already patched")
        return
    if "EXPERIMENT_CONFIGS" not in text:
        report(True, "run_test.py has no dataset table of its own (nothing to patch)")
        return

    source = (REPO / "run.py").read_text(encoding="utf-8")
    blocks = [f"\n{MARKER}"]
    for key, (_eval_file, _search_file, native) in DATASETS.items():
        native_config = _native_config(source, native)
        if native_config is None:
            continue
        question_type, operators = native_config
        blocks.append(
            f'EXPERIMENT_CONFIGS["{key}"] = ExperimentConfig(\n'
            f'    dataset="{key}",\n'
            f'    question_type="{question_type}",\n'
            f'    operators={operators!r},\n'
            f")"
        )
    anchor = re.search(r"\n(if __name__ == .__main__.:)", text)
    if anchor:
        text = text[: anchor.start()] + "\n" + "\n".join(blocks) + "\n" + text[anchor.start():]
    else:
        text = text.rstrip() + "\n" + "\n".join(blocks) + "\n"
    path.write_text(text, encoding="utf-8")
    report(MARKER in path.read_text(encoding="utf-8"), "run_test.py patched")


def patch_evaluator() -> None:
    path = REPO / "scripts" / "evaluator.py"
    text = path.read_text(encoding="utf-8")
    if MARKER in text:
        report(True, "evaluator already patched")
        return
    anchor = '            "MMLU_Pro": MMLUProBenchmark,\n        }'
    if anchor not in text:
        report(False, "evaluator dispatch anchor missing")
        return
    text = text.replace(
        anchor,
        anchor + "\n"
        f"        {MARKER}\n"
        "        from benchmarks.shared_benchmarks import SHARED_DATASET_CONFIGS\n"
        "        self.dataset_configs.update(SHARED_DATASET_CONFIGS)",
        1,
    )
    literal = re.search(r'DatasetType = Literal\[[^\]]*\]', text)
    if literal:
        keys = ", ".join(f'"{k}"' for k in DATASETS)
        text = text.replace(literal.group(0), literal.group(0)[:-1] + f", {keys}]", 1)
    path.write_text(text, encoding="utf-8")
    report(MARKER in path.read_text(encoding="utf-8"), "evaluator patched")


# The canonical rows already carry the field names DiverseFlow's benchmarks read
# (math/amc -> problem, drop -> context, mbpp -> prompt, mmlu_pro -> question),
# verified against the authors' own splits, so only AMC needs an alias.
FIELD_MAP = {
    "SHARED_AMC": lambda row: {**row, "question": row["problem"]},
}


def write_data() -> None:
    # The evaluator resolves f"{dataset.lower()}{_test|_validate}.jsonl" against
    # the FlowBank repo root, next to the authors' own splits. The SHARED_ prefix
    # is what keeps these from overwriting math_test.jsonl and friends.
    out_dir = FLOWBANK / "datasets"
    out_dir.mkdir(parents=True, exist_ok=True)
    written = 0
    for key, (eval_file, search_file, _native) in DATASETS.items():
        for suffix, source_name in (("test", eval_file), ("validate", search_file)):
            source = DATA / source_name
            if not source.exists():
                report(False, f"missing shared split {source_name}")
                continue
            adapt = FIELD_MAP.get(key, lambda row: row)
            target = out_dir / f"{key.lower()}_{suffix}.jsonl"
            with source.open(encoding="utf-8") as src, target.open("w", encoding="utf-8") as dst:
                for line in src:
                    if not line.strip():
                        continue
                    dst.write(json.dumps(adapt(json.loads(line)), ensure_ascii=False) + "\n")
            written += 1
    report(written == 2 * len(DATASETS), f"data written ({written} files in datasets/)")


def seed_workspaces() -> None:
    base = REPO / "workspace"
    for key, (_eval_file, _search_file, native) in DATASETS.items():
        source = base / native / "workflows"
        if not source.exists():
            report(False, f"workspace source {native} missing")
            continue
        target = base / key / "workflows"

        # A failed round leaves empty round_N dirs and a results.json the optimiser
        # then cannot read. Reset only when there is no seed graph, so a real
        # optimisation history is never discarded.
        if target.exists() and not (target / "round_1" / "graph.py").exists():
            shutil.rmtree(target)
        if (target / "round_1" / "graph.py").exists():
            report(True, f"workspace {key} already seeded")
            continue

        target.mkdir(parents=True, exist_ok=True)
        for part in ("round_1", "template"):
            if (source / part).exists():
                shutil.copytree(source / part, target / part)
        for name in ("__init__.py",):
            if (base / native / name).exists():
                shutil.copyfile(base / native / name, base / key / name)

        # graph.py imports its operators by absolute module path, so the copies
        # must point at their own directory or a dataset would silently execute
        # another one's operators and prompts.
        #
        # The prefix is matched generically rather than as f"workspace.{native}."
        # because the shipped AMC seed imports `workspace_qwen3.MATH...` -- a
        # package name that exists nowhere in the repo and a dataset that is not
        # AMC. As shipped, DiverseFlow's AMC seed cannot be imported at all; a
        # rewrite keyed on the exact native name silently left it that way.
        rewritten = 0
        for path in sorted(target.rglob("*.py")):
            body = path.read_text(encoding="utf-8")
            new_body = WORKSPACE_IMPORT.sub(f"workspace.{key}.workflows.", body)
            if new_body != body:
                path.write_text(new_body, encoding="utf-8")
                rewritten += 1
        report((target / "round_1" / "graph.py").exists(),
               f"workspace {key} seeded from {native} ({rewritten} import path(s) rewritten)")


# The optimizer is shown each operator's *call* signature and never its
# constructor. That omission is invisible with a strong optimizer and fatal with a
# weak one, and the evidence is a controlled comparison: given the identical
# operator description, Qwen3-8B wrote `operator.ScEnsemble(self.llm)` correctly
# inside FlowBank's DiverseFlow -- whose seed workflow already contains that exact
# line -- and `operator.ScEnsemble()` inside AFlow, whose MATH seed instantiates
# only Custom. The model was left to generalise the construction convention from
# one example, and did not. Every round that added an operator therefore died with
# TypeError and scored None, leaving AFlow reporting its seed workflow's score.
#
# Documenting the constructor is preferred over editing the seed workflow: the
# workflow is the method's starting point and its score has to stay comparable,
# whereas this is a factual gap in a field that already claims to state the
# interface. It says nothing about which workflow to build.
#
# The signature is derived from the operator source, never assumed -- a wrong
# constructor in the documentation would be worse than none.
def _required_init_args(sources, class_name: str) -> str | None:
    for path in sources:
        if not path.exists():
            continue
        text = path.read_text(encoding="utf-8")
        block = re.search(rf"class {re.escape(class_name)}\b[^\n]*:\n(.*?)(?=\nclass |\Z)", text, re.S)
        if not block:
            continue
        init = re.search(r"def __init__\(self,([^)]*)\)", block.group(1))
        if not init:
            continue
        required = []
        for raw in init.group(1).split(","):
            raw = raw.strip()
            if not raw or "=" in raw:
                continue
            required.append(raw.split(":")[0].strip())
        if required == ["llm"]:
            return "self.llm"
        return None if required else ""
    return None


def document_operator_constructors() -> None:
    added = already = 0
    for json_path in sorted((REPO / "workspace").glob("SHARED_*/workflows/template/operator.json")):
        sources = [json_path.with_name("operator.py"), REPO / "scripts" / "operators.py"]
        data = json.loads(json_path.read_text(encoding="utf-8"))
        dirty = False
        for name, entry in data.items():
            interface = entry.get("interface", "")
            if "constructed as" in interface:
                already += 1
                continue
            args = _required_init_args(sources, name)
            if args is None:
                report(False, f"{json_path.parent.parent.parent.name}/{name}: "
                              "constructor not derivable from source, left undocumented")
                continue
            entry["interface"] = f"constructed as operator.{name}({args}); called as {interface}"
            dirty = True
            added += 1
        if dirty:
            json_path.write_text(json.dumps(data, indent=4, ensure_ascii=False), encoding="utf-8")
    report(added + already > 0,
           f"operator constructors documented ({added} added, {already} already)")


# The Test operator lets a workflow run the problem's public tests before
# answering. It resolves them through extract_test_cases_from_jsonl(entry_point,
# dataset), whose file_map is hardcoded to humaneval / mbpp / livecodebench /
# codeforces -- SHARED_MBPP is not there, so the lookup falls through and returns
# None, and the operator's next line `for test_case in test_cases:` raises
# "'NoneType' object is not iterable".
#
# That is not a crash anyone sees: the exception escapes the workflow, the
# benchmark records it as a failed sample, and the round scores exactly 0.0000 on
# all 256 problems. Observed on FlowBank/MBPP as [0.6992, 0, 0, 0, 0, 0, 0, 0, 0]
# -- only the seed round, which never calls Test, survived. AFlow is affected too,
# and worse: its file_map points at data/datasets/mbpp_public_test.jsonl, a file
# the repo does not ship at all.
#
# The asserts must call `candidate`, not the real function name: the wrapper is
# `def check(candidate): <test_case>` invoked as `check(<entry_point>)`.
MBPP_TEST_MAP_ENTRY = '"SHARED_MBPP": "shared_mbpp_public_test.jsonl",'


def write_mbpp_public_tests() -> None:
    import re as _re

    out_path = FLOWBANK / "datasets" / "shared_mbpp_public_test.jsonl"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    written = 0
    seen: set[str] = set()
    collisions: list[str] = []
    with out_path.open("w", encoding="utf-8") as handle:
        for name in ("mbpp.jsonl", "mbpp_search.jsonl"):
            source = DATA / name
            if not source.exists():
                report(False, f"missing shared split {name}")
                continue
            with source.open(encoding="utf-8") as fh:
                for line in fh:
                    if not line.strip():
                        continue
                    row = json.loads(line)
                    entry = row.get("entry_point")
                    tests = row.get("test_list") or []
                    if not entry or not tests:
                        continue
                    if entry in seen:
                        # First-wins. The operator's signature is
                        # test(problem, solution, entry_point) -- there is no
                        # task_id -- so two MBPP problems sharing a function name
                        # are indistinguishable to it. Counted and reported rather
                        # than hidden: the authors' own file has the same ambiguity
                        # (427 entries for 974 tasks). Final scoring is unaffected;
                        # only the workflow's own self-check can be misled.
                        collisions.append(entry)
                        continue
                    seen.add(entry)
                    renamed = [_re.sub(rf"\b{_re.escape(entry)}\b", "candidate", t) for t in tests]
                    handle.write(json.dumps({"entry_point": entry, "test": renamed},
                                            ensure_ascii=False) + "\n")
                    written += 1
    report(written > 0, f"MBPP public tests -> {out_path.relative_to(ROOT)} "
           f"({written} entries, {len(collisions)} name collisions skipped)")

    code_path = REPO / "scripts" / "utils" / "code.py"
    text = code_path.read_text(encoding="utf-8")
    if "SHARED_MBPP" in text:
        report(True, "code.py already registers SHARED_MBPP")
        return
    anchor = "    file_map = {\n"
    if anchor not in text:
        report(False, "code.py file_map anchor missing")
        return
    text = text.replace(anchor, anchor + f"        {MBPP_TEST_MAP_ENTRY}  # shared-layer shim\n", 1)
    code_path.write_text(text, encoding="utf-8")
    report("SHARED_MBPP" in code_path.read_text(encoding="utf-8"),
           "code.py registers SHARED_MBPP")


# FlowBank's selector needs query embeddings, and build_selector_data.py offers
# only two backends: `openai` (text-embedding-3-small, no key available here) and
# `random`, which the script's own help calls out as "does not match the paper
# (random query features)". Random vectors would gut the method: QueryMatching
# exists precisely to pick a workflow from the query's semantics, so with random
# features the selector can only learn an input-independent preference.
#
# A local MiniLM backend is added instead. This is not a favour to FlowBank -- it
# is the encoder five of the other six methods already use by their authors' own
# choice (G-Designer, CARD, MasRouter, MaAS, DAAO all instantiate
# SentenceTransformer('all-MiniLM-L6-v2')), so it keeps one text encoder across
# the whole comparison. And the direction is conservative: MiniLM is 384-dim and
# 6 layers against text-embedding-3-small's 1536, so if anything this understates
# FlowBank relative to its paper.
MINILM_BACKEND = '''

def embed_minilm(texts, model_path):
    """Local sentence-transformers embeddings -- see shims/diverseflow/install.py.

    Chosen so that every method in the comparison shares one text encoder, and
    because no embedding API is reachable from this host. Deterministic: the
    encoder is frozen and inference-only.
    """
    from sentence_transformers import SentenceTransformer

    model = SentenceTransformer(model_path, device="cpu")
    vectors = model.encode([str(t) for t in texts], convert_to_numpy=True,
                           show_progress_bar=False)
    return np.asarray(vectors, dtype=np.float64)
'''


def patch_embedding_backend() -> None:
    path = REPO.parent / "data_processing" / "build_selector_data.py"
    if not path.exists():
        report(False, "build_selector_data.py missing")
        return
    text = path.read_text(encoding="utf-8")
    if "def embed_minilm" not in text:
        anchor = "def resolve_embedding_creds(args, ap):"
        if anchor not in text:
            report(False, "embedding helper anchor missing")
            return
        text = text.replace(anchor, MINILM_BACKEND.strip("\n") + "\n\n\n" + anchor, 1)

        choices = 'ap.add_argument("--embedding-backend", choices=["random", "openai"], default="random")'
        if choices not in text:
            report(False, "embedding-backend argument not found")
            return
        text = text.replace(
            choices,
            'ap.add_argument("--embedding-backend", choices=["random", "openai", "minilm"],\n'
            '                    default="random")\n'
            '    ap.add_argument("--minilm-path",\n'
            '                    default=str(Path(__file__).resolve().parents[2]\n'
            '                                / "shared" / "models" / "all-MiniLM-L6-v2"),\n'
            '                    help="local sentence-transformers model for --embedding-backend minilm")',
            1,
        )

        dispatch = '    if args.embedding_backend == "random":'
        if dispatch not in text:
            report(False, "embedding dispatch not found")
            return
        text = text.replace(
            dispatch,
            '    if args.embedding_backend == "minilm":\n'
            '        q_emb = embed_minilm(queries, args.minilm_path)\n'
            '        w_emb = embed_minilm(desc_text, args.minilm_path)\n'
            '        t_emb = embed_minilm([args.task_description or args.task_id], args.minilm_path)[0]\n'
            + dispatch,
            1,
        )

    # The inserted MiniLM branch and the author's random/OpenAI branch must be
    # one mutually exclusive chain. An earlier installer left the author's
    # `if random` unchanged, so a successful MiniLM embedding was immediately
    # followed by the OpenAI branch's `else` and failed as an unknown backend.
    broken_dispatch = (
        '        t_emb = embed_minilm([args.task_description or args.task_id], '
        'args.minilm_path)[0]\n'
        '    if args.embedding_backend == "random":'
    )
    fixed_dispatch = broken_dispatch.replace("\n    if args.embedding_backend", "\n    elif args.embedding_backend")
    text = text.replace(broken_dispatch, fixed_dispatch, 1)
    if "from pathlib import Path" not in text:
        text = "from pathlib import Path\n" + text
    path.write_text(text, encoding="utf-8")
    final = path.read_text(encoding="utf-8")
    report("def embed_minilm" in final and '"minilm"' in final
           and 'elif args.embedding_backend == "random":' in final,
           "MiniLM embedding backend added to build_selector_data.py")


def verify_syntax() -> None:
    for relative in PATCHED_SOURCES:
        path = REPO / relative
        if not path.exists():
            report(False, f"missing {relative}")
            continue
        try:
            ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        except SyntaxError as exc:
            report(False, f"{relative} does not compile: line {exc.lineno}: {exc.msg}")
        else:
            report(True, f"{relative} compiles")


def patch_namespace_override() -> None:
    """Let SHIM_BASE_URL win over config2.yaml, so accounting reaches the cell.

    FlowBank's generated-code execution is left alone -- its Test operator already
    times out per case and rebuilds its pool, so a hang costs a leaked process
    rather than the job. Only the URL is made per-job here.
    """
    outcome = namespace_patch.patch_file(
        REPO / "scripts" / "async_llm.py", "create_llm_instance", "llm_config")
    report(outcome in ("patched", "already"),
           f"namespace override in create_llm_instance ({outcome})")


def patch_indented_code() -> None:
    """Preserve complete functions with a uniform outer indent."""
    path = REPO / "scripts" / "utils" / "sanitize.py"
    outcome = dedent_patch.patch_sanitize_file(path)
    if outcome == "patched":
        verify_syntax()
    report(outcome in ("patched", "already"),
           f"sanitize preserves uniformly indented model code ({outcome})")


HARD_EXIT_MARKER = "# --- shared-layer shim (agent_wf_v2) --- hard exit v1"


def patch_hard_exit() -> None:
    """Exit the process the moment run.py's work is done.

    flowbank/math finished everything -- 16 converged rounds, results.json,
    coverage matrix, its own "Visualization generation completed" banner -- and
    then sat for two hours without exiting. The SIGUSR1 stack shows why: a
    leftover round-9 graph task blocked in Programmer.exec_code on a broken
    ProcessPoolExecutor (tenacity retrying around operators.py:234), and that
    non-daemon pool machinery keeps the interpreter alive. The artefacts are
    complete and flushed by that point, so a hard exit loses nothing; waiting
    loses the sweep slot for as long as nobody notices.
    """
    path = REPO / "run.py"
    text = path.read_text(encoding="utf-8")
    if HARD_EXIT_MARKER in text:
        report(True, "hard exit already installed")
        return
    # run.py has no __main__ guard; its final statement is the optimize call
    # itself, indented inside the entry block. Anchoring on that line keeps the
    # exit at the same indentation, immediately after the work returns.
    anchor = '    optimizer.optimize("Graph")'
    if anchor not in text:
        report(False, "run.py optimize call not found")
        return
    replacement = (anchor + "\n"
                   f"    {HARD_EXIT_MARKER}\n"
                   "    import os as _shim_os, sys as _shim_sys\n"
                   "    _shim_sys.stdout.flush(); _shim_sys.stderr.flush()\n"
                   "    _shim_os._exit(0)")
    text = text[: text.rfind(anchor)] + text[text.rfind(anchor):].replace(anchor, replacement, 1)
    path.write_text(text, encoding="utf-8")
    report(HARD_EXIT_MARKER in path.read_text(encoding="utf-8"), "hard exit installed")


def check() -> None:
    print("\n[diverseflow] verification")
    verify_syntax()
    report((REPO / "config" / "config.yaml").exists(), "config.yaml")
    run_text = (REPO / "run.py").read_text(encoding="utf-8")
    report(MARKER in run_text, "run.py patched")
    report(MARKER in (REPO / "scripts" / "evaluator.py").read_text(encoding="utf-8"),
           "evaluator patched")
    sanitizer = REPO / "scripts" / "utils" / "sanitize.py"
    report(sanitizer.exists() and "_shim_dedent_code(code)" in sanitizer.read_text(encoding="utf-8"),
           "sanitize preserves uniformly indented model code")
    selector = (REPO.parent / "data_processing" / "build_selector_data.py").read_text(
        encoding="utf-8"
    )
    report(
        'if args.embedding_backend == "minilm":' in selector
        and 'elif args.embedding_backend == "random":' in selector,
        "MiniLM selector dispatch is mutually exclusive",
    )
    for key, (_eval_file, _search_file, native) in DATASETS.items():
        report(f'"{key}"' in run_text, f"{key} registered")
        graph = REPO / "workspace" / key / "workflows" / "round_1" / "graph.py"
        ok = graph.exists()
        report(ok, f"workspace {key} seed graph")
        if ok:
            # Assert on every module prefix found, not just the native name: the
            # earlier version checked for f"workspace.{native}." only and passed a
            # seed that imported workspace_qwen3.MATH instead.
            prefixes = set(WORKSPACE_IMPORT.findall(graph.read_text(encoding="utf-8")))
            expected = {f"workspace.{key}.workflows."}
            report(prefixes <= expected,
                   f"workspace {key} imports only its own operators"
                   + ("" if prefixes <= expected else f" (found {sorted(prefixes - expected)})"))
        for suffix in ("test", "validate"):
            path = FLOWBANK / "datasets" / f"{key.lower()}_{suffix}.jsonl"
            report(path.exists() and path.stat().st_size > 0, f"data {path.name}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    if not REPO.exists():
        report(False, f"missing {REPO}")
    elif args.check:
        check()
    else:
        print("[diverseflow] installing")
        install_files()
        patch_run()
        patch_run_test()
        patch_evaluator()
        write_data()
        seed_workspaces()
        document_operator_constructors()
        write_mbpp_public_tests()
        patch_embedding_backend()
        patch_indented_code()
        patch_namespace_override()
        patch_hard_exit()
        write_config()
        verify_syntax()

    print("\n" + "=" * 60)
    if problems:
        print(f"DiverseFlow shim: {len(problems)} problem(s)")
        for item in problems:
            print("  -", item)
        sys.exit(1)
    print("DiverseFlow shim OK")


if __name__ == "__main__":
    main()
