#!/usr/bin/env python3
"""Install the shared-layer shim into AFlow.

Four things happen:

1. shared benchmark classes are added (see shared_benchmarks.py for why AFlow
   needs a scoring shim rather than just data);
2. the evaluator's dispatch table and run.py's EXPERIMENT_CONFIGS gain five
   entries -- note the repo ships `benchmarks/amc.py` but never registered AMC,
   so AMC was unreachable even before we arrived;
3. data files are *written*, not linked, because the field names differ per
   benchmark: AFlow's amc.py reads `problem["question"]` while the canonical
   split calls it `problem`. Adapting here keeps the canonical data and its
   sha256 untouched;
4. `download(["datasets"], ...)` is made non-fatal: AFlow's data lives on Google
   Drive, which is unreachable from this host, and the call otherwise aborts
   every run before it starts.

    python shims/aflow/install.py [--check]
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import exec_guard_patch  # noqa: E402
import dedent_patch  # noqa: E402
import namespace_patch  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
HERE = Path(__file__).resolve().parent
REPO = ROOT / "third_party" / "aflow"
DATA = ROOT / "shared" / "data"

MARKER = "# --- shared-layer shim (agent_wf_v2) ---"

# key -> (eval split file, search split file, question_type)
DATASETS = {
    "SHARED_MATH": ("math.jsonl", "math_search.jsonl", "math"),
    # AMC adopted verbatim from FlowBank's shipped split (2026-08-24).
    "SHARED_AMC": ("amc.jsonl", "amc_search.jsonl", "math"),
    "SHARED_MBPP": ("mbpp.jsonl", "mbpp_search.jsonl", "code"),
    "SHARED_DROP": ("drop.jsonl", "drop_search.jsonl", "qa"),
    "SHARED_MMLUPRO": ("mmlu_pro.jsonl", "mmlu_pro_search.jsonl", "qa"),
}

MATH_OPERATORS = ["Custom", "ScEnsemble", "Programmer"]
CODE_OPERATORS = ["Custom", "CustomCodeGenerate", "ScEnsemble", "Test"]
QA_OPERATORS = ["Custom", "AnswerGenerate", "ScEnsemble"]

problems: list[str] = []


def report(ok: bool, message: str) -> None:
    print(f"  [{'ok' if ok else 'FAIL'}] {message}")
    if not ok:
        problems.append(message)



CONFIG_TEMPLATE = """# Generated by shims/aflow/install.py -- do not hand-edit.
#
# AFlow ships only config2.example.yaml, so without this file LLMsConfig.default()
# finds nothing and every run dies before it starts. Its schema is just a `models`
# map (no `llm` section and no stream flag), and both the optimizer and the
# executor point at the same local Qwen3-8B behind the experiment proxy, which
# forces temperature=0 and disables thinking.
models:
  qwen3-8b:
    api_type: "openai"
    # Explicit: without it metagpt sends model=None and the proxy refuses the
    # call rather than guessing.
    model: "qwen3-8b"
    base_url: "http://127.0.0.1:18080/train/aflow/v1"
    api_key: "local"
    temperature: 0
"""


def write_config() -> None:
    config_dir = REPO / "config"
    config_dir.mkdir(parents=True, exist_ok=True)
    path = config_dir / "config2.yaml"
    path.write_text(CONFIG_TEMPLATE, encoding="utf-8")
    report("qwen3-8b" in path.read_text(encoding="utf-8"), f"config -> {path.relative_to(ROOT)}")


def install_files() -> None:
    target = REPO / "benchmarks" / "shared_benchmarks.py"
    shutil.copyfile(HERE / "shared_benchmarks.py", target)
    report(target.exists(), f"{target.relative_to(ROOT)}")


def patch_evaluator() -> None:
    path = REPO / "scripts" / "evaluator.py"
    text = path.read_text(encoding="utf-8")
    if MARKER in text:
        report(True, "evaluator already patched")
        return
    anchor = '            "LiveCodeBench": LiveCodeBench,\n        }'
    if anchor not in text:
        report(False, "evaluator anchor missing")
        return
    text = text.replace(
        anchor,
        '            "LiveCodeBench": LiveCodeBench,\n        }\n'
        f"        {MARKER}\n"
        "        from benchmarks.shared_benchmarks import SHARED_DATASET_CONFIGS\n"
        "        self.dataset_configs.update(SHARED_DATASET_CONFIGS)",
        1,
    )
    literal = re.search(r'DatasetType = Literal\[[^\]]*\]', text)
    if literal:
        keys = ", ".join(f'"{k}"' for k in DATASETS)
        text = text.replace(literal.group(0), literal.group(0)[:-1] + f", {keys}]", 1)
    path.write_text(text, encoding="utf-8")
    report(MARKER in path.read_text(encoding="utf-8"), "evaluator patched")


def patch_run() -> None:
    path = REPO / "run.py"
    text = path.read_text(encoding="utf-8")
    if MARKER in text:
        report(True, "run.py already patched")
        return

    # Google Drive is unreachable here; a failed dataset download must not abort
    # the run, since the shim supplies the data itself.
    # A function replacement, not a template string: in a replacement template
    # \" survives as a literal backslash-quote, which is how an earlier revision
    # wrote a SyntaxError into run.py -- and the marker-based check still passed,
    # because it only looked for a string and never compiled the result.
    def _guard_download(match: re.Match) -> str:
        indent = match.group(1)
        return (
            f"{indent}try:\n"
            f"{indent}    download([\"datasets\"], force_download=args.if_force_download)\n"
            f"{indent}except Exception as _download_error:  # shim: data is local\n"
            f"{indent}    print(f\"skipping dataset download: {{_download_error}}\")"
        )

    text, count = re.subn(
        r"^(\s*)download\(\[\"datasets\"\], force_download=args\.if_force_download\).*$",
        _guard_download,
        text,
        count=1,
        flags=re.MULTILINE,
    )
    if count == 0:
        report(False, "download() anchor missing")

    blocks = [f"\n{MARKER}"]
    for key, (_eval_file, _search_file, qtype) in DATASETS.items():
        operators = {"math": MATH_OPERATORS, "code": CODE_OPERATORS, "qa": QA_OPERATORS}[qtype]
        blocks.append(
            f'EXPERIMENT_CONFIGS["{key}"] = ExperimentConfig(\n'
            f'    dataset="{key}",\n'
            f'    question_type="{"code" if qtype == "code" else "math" if qtype == "math" else "qa"}",\n'
            f'    operators={operators!r},\n'
            f")"
        )
    # Insert after the EXPERIMENT_CONFIGS literal so argparse choices see them.
    anchor = re.search(r"\n(if __name__ == .__main__.:)", text)
    injection = "\n".join(blocks) + "\n"
    if anchor:
        text = text[: anchor.start()] + "\n" + injection + text[anchor.start():]
    else:
        report(False, "run.py main guard not found")
    path.write_text(text, encoding="utf-8")
    report(MARKER in path.read_text(encoding="utf-8"), "run.py patched")


# AFlow's per-benchmark field names differ from the canonical split's.
FIELD_MAP = {
    "SHARED_AMC": lambda row: {**row, "question": row["problem"]},
}


def write_data() -> None:
    out_dir = REPO / "data" / "datasets"
    out_dir.mkdir(parents=True, exist_ok=True)
    for key, (eval_file, search_file, _qtype) in DATASETS.items():
        for suffix, source_name in (("test", eval_file), ("validate", search_file)):
            source = DATA / source_name
            if not source.exists():
                report(False, f"missing shared split {source_name}")
                continue
            adapt = FIELD_MAP.get(key, lambda row: row)
            target = out_dir / f"{key.lower()}_{suffix}.jsonl"
            with source.open(encoding="utf-8") as src, target.open("w", encoding="utf-8") as dst:
                for line in src:
                    if not line.strip():
                        continue
                    dst.write(json.dumps(adapt(json.loads(line)), ensure_ascii=False) + "\n")
    # Counted by expected name, not by glob: shared_mbpp_public_test.jsonl lives in
    # this same directory and made a correct install report 11 of 10 files.
    expected = [f"{key.lower()}_{suffix}.jsonl"
                for key in DATASETS for suffix in ("test", "validate")]
    written = [name for name in expected if (out_dir / name).exists()]
    report(len(written) == len(expected),
           f"data written ({len(written)}/{len(expected)} files)")


# Files this installer rewrites. Anything it edits must still compile: a
# marker-string check cannot tell a working patch from one that wrote a
# SyntaxError, and the failure only surfaces much later as an unrelated-looking
# import error.
PATCHED_SOURCES = ("run.py", "scripts/evaluator.py", "scripts/optimizer.py",
                   "benchmarks/shared_benchmarks.py")


# AFlow optimises by rewriting a starting workflow, so each dataset needs
# workspace/<KEY>/workflows/{round_1,template}: round_1 holds the seed graph.py
# and prompt.py, template holds the operator implementations. Without it the run
# does not fail -- it logs "No module named workspace.SHARED_MATH.workflows.round_1.graph",
# scores every round None, and exits as if it had finished.
#
# Each shared dataset seeds from the author workspace for the closest benchmark.
# MMLU-Pro has no counterpart, so it takes HotpotQA's: both are QA and both use
# the Custom/AnswerGenerate/ScEnsemble operator set already registered for them
# in EXPERIMENT_CONFIGS. That is a declared substitution.
WORKSPACE_SOURCE = {
    "SHARED_MATH": "MATH",
    "SHARED_AMC": "MATH",
    "SHARED_MBPP": "MBPP",
    "SHARED_DROP": "DROP",
    "SHARED_MMLUPRO": "HotpotQA",
}


def seed_workspaces() -> None:
    base = REPO / "workspace"
    for key, source_name in WORKSPACE_SOURCE.items():
        source = base / source_name / "workflows"
        if not source.exists():
            report(False, f"workspace source {source_name} missing")
            continue
        target = base / key / "workflows"

        # A previous failed run leaves empty round_N dirs and a results.json the
        # optimiser then cannot read ("Error loading scores ... 'round'"). Reset
        # only when there is no seed graph, so a real optimisation history is
        # never discarded.
        if target.exists() and not (target / "round_1" / "graph.py").exists():
            shutil.rmtree(target)

        if (target / "round_1" / "graph.py").exists():
            report(True, f"workspace {key} already seeded")
            continue

        target.mkdir(parents=True, exist_ok=True)
        for part in ("round_1", "template"):
            if (source / part).exists():
                shutil.copytree(source / part, target / part)

        # graph.py imports its operators by absolute module path
        # (import workspace.MATH.workflows.template.operator), so the copies must
        # point at their own directory or every dataset would silently execute
        # MATH's operators and prompts.
        rewritten = 0
        for path in sorted(target.rglob("*.py")):
            text = path.read_text(encoding="utf-8")
            new_text = text.replace(f"workspace.{source_name}.", f"workspace.{key}.")
            if new_text != text:
                path.write_text(new_text, encoding="utf-8")
                rewritten += 1
        ok = (target / "round_1" / "graph.py").exists()
        report(ok, f"workspace {key} seeded from {source_name} ({rewritten} import path(s) rewritten)")


def check_workspaces() -> None:
    for key, source_name in WORKSPACE_SOURCE.items():
        graph = REPO / "workspace" / key / "workflows" / "round_1" / "graph.py"
        ok = graph.exists()
        report(ok, f"workspace {key} seed graph")
        if ok and f"workspace.{source_name}." in graph.read_text(encoding="utf-8"):
            report(False, f"workspace {key} still imports {source_name}'s operators")


# One sentence, taken verbatim from FlowBank/DiverseFlow's own optimiser prompt
# (scripts/prompts/optimize_prompt.py, "You MUST define every ..."), which its
# author added for exactly this failure.
#
# AFlow's template shows the optimiser this example:
#
#     response = await self.custom(input=problem, instruction=prompt_custom.XXX_PROMPT)
#
# `XXX_PROMPT` is a placeholder addressed to a human reader, and nothing in the
# template says the referenced variable has to be defined. Qwen3-8B copies the
# placeholder literally into the generated graph.py and never defines it in
# prompt.py, so every item of that round raises AttributeError and the round scores
# exactly 0.0000 -- measured 3 of 7 rounds on MMLU-Pro, 3 of 19 on DROP, and 3 of 12
# in an earlier full run. FlowBank, running the same 8B optimiser, wastes none: its
# author renamed the example to a real `SOLVE_PROMPT`, added this instruction twice,
# and made "has no attribute" a retry trigger.
#
# Why this counts as reproduction rather than improvement: AFlow's paper used a
# GPT-4o-class optimiser, which does not copy a placeholder. The trap is sprung by
# *our* substitution of an 8B for every method's optimiser, so leaving it in place
# would measure which prompt template survives a small model, not which method
# designs better workflows. The instruction is added; the example, the operators and
# the retry budget are left as the authors wrote them.
PROMPT_DEFINITION_RULE = (
    "\n**You MUST define every `prompt_custom.XXXX` variable you reference in the "
    "graph, inside the `<prompt>` section. For example, if the graph uses "
    "`prompt_custom.SOLVE_PROMPT`, then `<prompt>` must contain "
    "`SOLVE_PROMPT = \"...\"`. `XXX_PROMPT` above is a placeholder for a name you "
    "choose, not a variable that exists.**\n"
)


def patch_prompt_definition_rule() -> None:
    """Tell the optimiser that a referenced prompt variable has to be defined."""
    path = REPO / "scripts" / "prompts" / "optimize_prompt.py"
    if not path.exists():
        report(False, f"missing {path.relative_to(ROOT)}")
        return
    text = path.read_text(encoding="utf-8")
    if "placeholder for a name you" in text:
        report(True, "prompt-definition rule already present")
        return
    anchor = ("Note: In custom, the input and instruction are directly "
              "concatenated(instruction+input)")
    if anchor not in text:
        report(False, "WORKFLOW_CUSTOM_USE anchor missing; template may have changed")
        return
    text = text.replace(anchor, PROMPT_DEFINITION_RULE.lstrip("\n") + "\n" + anchor, 1)
    path.write_text(text, encoding="utf-8")
    import ast as _ast

    try:
        _ast.parse(path.read_text(encoding="utf-8"))
    except SyntaxError as exc:
        report(False, f"optimize_prompt.py does not parse after patching: {exc}")
        return
    report("placeholder for a name you" in path.read_text(encoding="utf-8"),
           "prompt-definition rule added to WORKFLOW_CUSTOM_USE")


def patch_retry_budget() -> None:
    """Give the optimiser more than one attempt, and count the failures.

    optimizer.py hardcodes max_retries = 1, so a single unusable generated graph
    ends the round with score None. With a GPT-4o-class optimiser that is rare;
    with Qwen3-8B it is not -- the smoke run produced
    `operator.ScEnsemble()` (missing the required llm argument) one line below a
    correct `operator.Custom(self.llm)` in the same file, twice in a row, and both
    rounds were discarded. Left alone, AFlow's reported number would be its seed
    workflow's score, which reads as "AFlow is not better" rather than "AFlow's
    generated graphs did not run".

    **The default stays the author's 1.** An earlier revision defaulted to 3, which
    was a value picked rather than derived -- and the run cited as evidence for it
    did not support it: rounds 2 and 3 both succeeded on the first attempt, and the
    two logged failures were the proxy's context-clamp bug (deterministic, so
    retrying could not help), not invalid graphs. With that bug fixed, the retry
    budget has no evidence behind it, so the author value is restored and the knob
    is left only as a declared lever.

    What remains unconditionally is the measurement: every failed attempt is
    appended to AFLOW_GRAPH_FAILURES, so the invalid-graph rate is a quantity we
    report rather than an impression. The retry does re-invoke _optimize_graph(),
    i.e. a fresh generation rather than a rerun of the same broken code, so raising
    the budget is meaningful if the rate turns out to be high.
    """
    path = REPO / "scripts" / "optimizer.py"
    text = path.read_text(encoding="utf-8")
    if "AFLOW_MAX_RETRIES" in text:
        report(True, "retry budget already patched")
        return
    old = "            max_retries = 1"
    if old not in text:
        report(False, "optimizer max_retries anchor missing")
        return
    text = text.replace(
        old,
        "            # shared-layer shim: see shims/aflow/install.py\n"
        "            max_retries = int(os.getenv(\"AFLOW_MAX_RETRIES\", \"1\"))",
        1,
    )
    log_old = '                    logger.info(f"Error occurred: {e}. Retrying... (Attempt {retry_count}/{max_retries})")'
    if log_old in text:
        text = text.replace(
            log_old,
            log_old + "\n"
            "                    _failure_log = os.getenv(\"AFLOW_GRAPH_FAILURES\", \"\")\n"
            "                    if _failure_log:  # shim: measure the invalid-graph rate\n"
            "                        try:\n"
            "                            with open(_failure_log, \"a\", encoding=\"utf-8\") as _fh:\n"
            "                                _fh.write(f\"{type(e).__name__}: {e}\" + chr(10))\n"
            "                        except OSError:\n"
            "                            pass",
            1,
        )
    if "\nimport os" not in text and not text.startswith("import os"):
        text = "import os  # shared-layer shim\n" + text
    path.write_text(text, encoding="utf-8")
    final = path.read_text(encoding="utf-8")
    report("AFLOW_MAX_RETRIES" in final and "AFLOW_GRAPH_FAILURES" in final,
           "retry budget = AFLOW_MAX_RETRIES (default 3), failures logged")


# The optimizer is shown each operator's *call* signature and never its
# constructor. That omission is invisible with a strong optimizer and fatal with a
# weak one, and the evidence is a controlled comparison: given the identical
# operator description, Qwen3-8B wrote `operator.ScEnsemble(self.llm)` correctly
# inside FlowBank's DiverseFlow -- whose seed workflow already contains that exact
# line -- and `operator.ScEnsemble()` inside AFlow, whose MATH seed instantiates
# only Custom. The model was left to generalise the construction convention from
# one example, and did not. Every round that added an operator therefore died with
# TypeError and scored None, leaving AFlow reporting its seed workflow's score.
#
# Documenting the constructor is preferred over editing the seed workflow: the
# workflow is the method's starting point and its score has to stay comparable,
# whereas this is a factual gap in a field that already claims to state the
# interface. It says nothing about which workflow to build.
#
# The signature is derived from the operator source, never assumed -- a wrong
# constructor in the documentation would be worse than none.
def _required_init_args(sources, class_name: str) -> str | None:
    for path in sources:
        if not path.exists():
            continue
        text = path.read_text(encoding="utf-8")
        block = re.search(rf"class {re.escape(class_name)}\b[^\n]*:\n(.*?)(?=\nclass |\Z)", text, re.S)
        if not block:
            continue
        init = re.search(r"def __init__\(self,([^)]*)\)", block.group(1))
        if not init:
            continue
        required = []
        for raw in init.group(1).split(","):
            raw = raw.strip()
            if not raw or "=" in raw:
                continue
            required.append(raw.split(":")[0].strip())
        if required == ["llm"]:
            return "self.llm"
        return None if required else ""
    return None


def document_operator_constructors() -> None:
    added = already = 0
    for json_path in sorted((REPO / "workspace").glob("SHARED_*/workflows/template/operator.json")):
        sources = [json_path.with_name("operator.py"), REPO / "scripts" / "operators.py"]
        data = json.loads(json_path.read_text(encoding="utf-8"))
        dirty = False
        for name, entry in data.items():
            interface = entry.get("interface", "")
            if "constructed as" in interface:
                already += 1
                continue
            args = _required_init_args(sources, name)
            if args is None:
                report(False, f"{json_path.parent.parent.parent.name}/{name}: "
                              "constructor not derivable from source, left undocumented")
                continue
            entry["interface"] = f"constructed as operator.{name}({args}); called as {interface}"
            dirty = True
            added += 1
        if dirty:
            json_path.write_text(json.dumps(data, indent=4, ensure_ascii=False), encoding="utf-8")
    report(added + already > 0,
           f"operator constructors documented ({added} added, {already} already)")


# The Test operator lets a workflow run the problem's public tests before
# answering. It resolves them through extract_test_cases_from_jsonl(entry_point,
# dataset), whose file_map is hardcoded to humaneval / mbpp / livecodebench /
# codeforces -- SHARED_MBPP is not there, so the lookup falls through and returns
# None, and the operator's next line `for test_case in test_cases:` raises
# "'NoneType' object is not iterable".
#
# That is not a crash anyone sees: the exception escapes the workflow, the
# benchmark records it as a failed sample, and the round scores exactly 0.0000 on
# all 256 problems. Observed on FlowBank/MBPP as [0.6992, 0, 0, 0, 0, 0, 0, 0, 0]
# -- only the seed round, which never calls Test, survived. AFlow is affected too,
# and worse: its file_map points at data/datasets/mbpp_public_test.jsonl, a file
# the repo does not ship at all.
#
# The asserts must call `candidate`, not the real function name: the wrapper is
# `def check(candidate): <test_case>` invoked as `check(<entry_point>)`.
MBPP_TEST_MAP_ENTRY = '"SHARED_MBPP": "data/datasets/shared_mbpp_public_test.jsonl",'


def write_mbpp_public_tests() -> None:
    import re as _re

    out_path = REPO / "data" / "datasets" / "shared_mbpp_public_test.jsonl"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    written = 0
    seen: set[str] = set()
    collisions: list[str] = []
    with out_path.open("w", encoding="utf-8") as handle:
        for name in ("mbpp.jsonl", "mbpp_search.jsonl"):
            source = DATA / name
            if not source.exists():
                report(False, f"missing shared split {name}")
                continue
            with source.open(encoding="utf-8") as fh:
                for line in fh:
                    if not line.strip():
                        continue
                    row = json.loads(line)
                    entry = row.get("entry_point")
                    tests = row.get("test_list") or []
                    if not entry or not tests:
                        continue
                    if entry in seen:
                        # First-wins. The operator's signature is
                        # test(problem, solution, entry_point) -- there is no
                        # task_id -- so two MBPP problems sharing a function name
                        # are indistinguishable to it. Counted and reported rather
                        # than hidden: the authors' own file has the same ambiguity
                        # (427 entries for 974 tasks). Final scoring is unaffected;
                        # only the workflow's own self-check can be misled.
                        collisions.append(entry)
                        continue
                    seen.add(entry)
                    renamed = [_re.sub(rf"\b{_re.escape(entry)}\b", "candidate", t) for t in tests]
                    handle.write(json.dumps({"entry_point": entry, "test": renamed},
                                            ensure_ascii=False) + "\n")
                    written += 1
    report(written > 0, f"MBPP public tests -> {out_path.relative_to(ROOT)} "
           f"({written} entries, {len(collisions)} name collisions skipped)")

    code_path = REPO / "scripts" / "utils" / "code.py"
    text = code_path.read_text(encoding="utf-8")
    if "SHARED_MBPP" in text:
        report(True, "code.py already registers SHARED_MBPP")
        return
    anchor = "    file_map = {\n"
    if anchor not in text:
        report(False, "code.py file_map anchor missing")
        return
    text = text.replace(anchor, anchor + f"        {MBPP_TEST_MAP_ENTRY}  # shared-layer shim\n", 1)
    code_path.write_text(text, encoding="utf-8")
    report("SHARED_MBPP" in code_path.read_text(encoding="utf-8"),
           "code.py registers SHARED_MBPP")


# Same fix as shims/maas_family/install.py, and the same source: FlowBank's own
# MMLU-Pro ScEnsemble (its commit dde948d). AFlow keeps one operator template per
# workspace, so unlike MaAS/DAAO this only has to touch the MMLU-Pro workspace and
# needs no runtime dataset test -- the file it lands in is used by nothing else.
#
# AFlow needs this even though its MMLU-Pro logs show no KeyError yet: the crash
# depends on whether a searched graph happens to call ScEnsemble on a lettered
# question, so its absence over 20 rounds is luck, not immunity. The guard costs
# nothing when the letter is valid.
#
# `problem` MUST keep a default. This workspace's template declares
# `__call__(self, solutions)` -- no problem argument at all -- and the operator
# description the optimiser reads documents it as `sc_ensemble(solutions)`. A
# first version of this patch made `problem` required, so every generated graph
# raised TypeError on its first call and all 252 items scored 0: eight consecutive
# rounds at exactly 0.0000, no exception surfaced anywhere, and the run terminated
# early on "convergence". A shadowing subclass must accept every call shape the
# class it shadows accepted; widening the signature is not a compatible change.
SCENSEMBLE_PATCH_MARKER = "# --- shared-layer shim (agent_wf_v2) --- scensemble v2"
SC_ENSEMBLE_NUMERIC_AFLOW = '''

# --- shared-layer shim (agent_wf_v2) --- scensemble v2
# MMLU-Pro label-space fix. The author operator above labels candidate solutions
# A, B, C and asks which letter is best; MMLU-Pro's own options are (A)-(J), so a
# reply of "E" means the question's option E and indexes a candidate that does not
# exist -- KeyError, and the sample is lost rather than merely scored wrong.
# Numeric labels remove the ambiguity. Lifted from FlowBank's operator for the
# same dataset; the author class above is left untouched and shadowed.
import re as _shim_re
import sys as _shim_sys
from pydantic import BaseModel as _ShimBaseModel, Field as _ShimField

# The question is optional, because the template's own SC_ENSEMBLE_PROMPT does not
# include it either -- this workspace's ensemble judges the candidates alone. Kept
# as a leading slot so a graph that does pass the problem loses nothing.
SC_ENSEMBLE_NUMERIC_PROMPT = """{question}Several solutions have been generated to address the given question. They are as follows:
{solutions}

Carefully evaluate these solutions and identify the answer that appears most frequently across them. This consistency in answers is crucial for determining the most reliable solution.

In the "thought" field, provide a detailed explanation of your thought process. In the "solution_number" field, output ONLY the numeric ID (1, 2, 3, etc.) corresponding to the most consistent solution. Do NOT output a letter - output the number only.
"""


class ScEnsembleNumericOp(_ShimBaseModel):
    thought: str = _ShimField(default="", description="The thought of the most consistent solution.")
    solution_number: str = _ShimField(default="", description="The number of the most consistent solution (1, 2, 3, etc.).")


class ScEnsemble(ScEnsemble):  # noqa: F811 - shadows the author class above
    # Default, not required: see the note in shims/aflow/install.py. The class this
    # shadows takes `solutions` alone, and the optimiser generates calls to match.
    async def __call__(self, solutions: List[str], problem: str = ""):
        answer_mapping = {}
        solution_text = ""
        for index, solution in enumerate(solutions):
            label = str(index + 1)
            answer_mapping[label] = index
            solution_text += f"{label}: \\n{str(solution)}\\n\\n\\n"

        question = f"Given the question described as follows: {problem}\\n" if problem else ""
        prompt = SC_ENSEMBLE_NUMERIC_PROMPT.format(question=question, solutions=solution_text)
        response = await self._fill_node(ScEnsembleNumericOp, prompt, mode="xml_fill")
        answer = str(response.get("solution_number", "")).strip()

        if answer in answer_mapping:
            return {"response": solutions[answer_mapping[answer]]}
        for token in _shim_re.findall(r"\\d+", answer):
            if token in answer_mapping:
                return {"response": solutions[answer_mapping[token]]}
        _shim_sys.stderr.write(
            f"[shared_shim] ScEnsemble got {answer!r}, not one of "
            f"{sorted(answer_mapping)}; falling back to the first solution\\n")
        return {"response": solutions[0]}
'''


def patch_scensemble_labels() -> None:
    """Install the MMLU-Pro label-space guard in the MMLU-Pro workspace only."""
    targets = sorted(REPO.glob("workspace/SHARED_MMLUPRO/**/template/operator.py"))
    if not targets:
        report(False, "no SHARED_MMLUPRO operator template to patch")
        return
    patched = already = upgraded = 0
    for path in targets:
        text = path.read_text(encoding="utf-8")
        if SCENSEMBLE_PATCH_MARKER in text:
            already += 1
            continue
        if "ScEnsembleNumericOp" in text:
            # An earlier version of this patch is present. Truncate at its marker
            # and re-append rather than skipping: "already patched" was how the
            # broken first version stayed in place through a reinstall, and the
            # only symptom was every generated round scoring exactly zero.
            head = text.split("# --- shared-layer shim (agent_wf_v2) ---")[0]
            text = head.rstrip() + "\n"
            upgraded += 1
        elif "class ScEnsemble" not in text:
            report(False, f"{path} has no ScEnsemble to shadow")
            continue
        path.write_text(text + SC_ENSEMBLE_NUMERIC_AFLOW, encoding="utf-8")
        patched += 1
    import ast as _ast

    for path in targets:
        try:
            _ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        except SyntaxError as exc:
            report(False, f"{path.name} does not compile after patching: {exc}")
            return
    report(True, f"MMLU-Pro ScEnsemble label guard ({patched} patched"
                 f"{f', {upgraded} upgraded from an older patch' if upgraded else ''}"
                 f", {already} already current)")


def verify_syntax() -> None:
    import ast as _ast

    for relative in PATCHED_SOURCES:
        path = REPO / relative
        if not path.exists():
            report(False, f"missing {relative}")
            continue
        try:
            _ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        except SyntaxError as exc:
            report(False, f"{relative} does not compile: line {exc.lineno}: {exc.msg}")
        else:
            report(True, f"{relative} compiles")


def patch_namespace_override() -> None:
    """Let SHIM_BASE_URL win over config2.yaml, so accounting reaches the cell."""
    outcome = namespace_patch.patch_file(
        REPO / "scripts" / "async_llm.py", "create_llm_instance", "llm_config")
    report(outcome in ("patched", "already"),
           f"namespace override in create_llm_instance ({outcome})")


def patch_code_execution() -> None:
    """Bound execution of model-written code with a process that can be killed.

    AFlow has the same non-terminating pattern as MaAS -- ProcessPoolExecutor in a
    `with` block, cancelled but not killed on timeout, so the block's exit waits on
    the runaway child forever -- and additionally runs generated test cases through
    a bare `exec(test_code, globals())` with no timeout at all.
    """
    targets = sorted((REPO / "workspace").glob("*/workflows/template/operator.py"))
    targets += [p for p in [REPO / "scripts" / "operators.py",
                            REPO / "scripts" / "operator.py"] if p.exists()]
    tally: dict[str, int] = {}
    for path in targets:
        outcome = exec_guard_patch.patch_file(path)
        tally[outcome] = tally.get(outcome, 0) + 1
    report(tally.get("patched", 0) + tally.get("already", 0) > 0,
           "generated-code execution guarded ("
           + ", ".join(f"{v} {k}" for k, v in sorted(tally.items())) + ")")


def patch_indented_code() -> None:
    """Preserve complete functions with a uniform outer indent."""
    path = REPO / "scripts" / "utils" / "sanitize.py"
    outcome = dedent_patch.patch_sanitize_file(path)
    if outcome == "patched":
        verify_syntax()
    report(outcome in ("patched", "already"),
           f"sanitize preserves uniformly indented model code ({outcome})")


def check() -> None:
    print("\n[aflow] verification")
    verify_syntax()
    check_workspaces()
    templates = list(REPO.glob("workspace/SHARED_MMLUPRO/**/template/operator.py"))
    guards = [p for p in templates if SCENSEMBLE_PATCH_MARKER in p.read_text(encoding="utf-8")]
    report(bool(guards) and len(guards) == len(templates),
           f"MMLU-Pro ScEnsemble label guard at current version "
           f"({len(guards)}/{len(templates)} file(s))")
    # The signature must stay compatible with the class it shadows. A required
    # `problem` made every generated graph raise TypeError, which showed up only as
    # eight rounds of exactly 0.0000 -- so it is asserted, not assumed.
    widened = [p for p in guards
               if "async def __call__(self, solutions: List[str], problem: str)" in
               p.read_text(encoding="utf-8").split(SCENSEMBLE_PATCH_MARKER)[-1]]
    rule = (REPO / "scripts" / "prompts" / "optimize_prompt.py")
    report(rule.exists() and "placeholder for a name you" in rule.read_text(encoding="utf-8"),
           "optimiser told to define every prompt_custom variable it references")
    report(not widened,
           "shadowing subclass keeps `problem` optional"
           + ("" if not widened else f" (VIOLATED in {len(widened)} file(s))"))
    report((REPO / "benchmarks" / "shared_benchmarks.py").exists(), "shared_benchmarks.py")
    report((REPO / "config" / "config2.yaml").exists(), "config2.yaml")
    report(MARKER in (REPO / "scripts" / "evaluator.py").read_text(encoding="utf-8"), "evaluator patched")
    sanitizer = REPO / "scripts" / "utils" / "sanitize.py"
    report(sanitizer.exists() and "_shim_dedent_code(code)" in sanitizer.read_text(encoding="utf-8"),
           "sanitize preserves uniformly indented model code")
    run_text = (REPO / "run.py").read_text(encoding="utf-8")
    report(MARKER in run_text, "run.py patched")
    report("skipping dataset download" in run_text, "download() made non-fatal")
    for key in DATASETS:
        for suffix in ("test", "validate"):
            path = REPO / "data" / "datasets" / f"{key.lower()}_{suffix}.jsonl"
            report(path.exists() and path.stat().st_size > 0, f"data {path.name}")
    amc = REPO / "data" / "datasets" / "shared_amc_test.jsonl"
    if amc.exists():
        with amc.open(encoding="utf-8") as handle:
            row = json.loads(handle.readline())
        report("question" in row, "AMC has the 'question' field AFlow reads")


MBPP_DAEMON_MARKER = "# --- shared-layer shim (agent_wf_v2) --- mbpp daemon guard v1"


def patch_mbpp_daemon_thread(repo) -> None:
    """Daemonise the mbpp benchmark's test-runner thread.

    benchmarks/mbpp.py run_with_timeout starts a plain threading.Thread for the
    generated code + asserts and abandons it on timeout. The thread is
    non-daemon, so every hung generated function (an infinite get_ludic on
    2026-08-24) leaks a live thread; they accumulate over a search and finally
    keep the interpreter alive after run.py ends -- aflow/mbpp sat wire-quiet
    for 3 hours twice. Same shape and same fix as the G-Designer family's
    guard thread (shims/gdesigner_family patch_daemon_guard).
    """
    import ast as _ast
    path = repo / "benchmarks" / "mbpp.py"
    text = path.read_text(encoding="utf-8")
    if MBPP_DAEMON_MARKER in text:
        report(True, "mbpp guard thread already daemonised")
        return
    anchor_line = "        thread = threading.Thread(target=target)\n        thread.start()"
    if anchor_line not in text:
        report(False, "mbpp daemonise: anchor not found")
        return
    text = text.replace(anchor_line,
                        "        thread = threading.Thread(target=target)\n"
                        "        " + MBPP_DAEMON_MARKER + "\n"
                        "        thread.daemon = True\n        thread.start()", 1)
    try:
        _ast.parse(text)
    except SyntaxError as exc:
        report(False, f"mbpp daemonise: does not parse: {exc}")
        return
    path.write_text(text, encoding="utf-8")
    report(True, "mbpp guard thread daemonised")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if not args.check:
        patch_mbpp_daemon_thread(REPO)

    if not REPO.exists():
        report(False, f"missing {REPO}")
    elif args.check:
        check()
    else:
        print("[aflow] installing")
        install_files()
        patch_evaluator()
        patch_run()
        write_data()
        write_config()
        seed_workspaces()
        document_operator_constructors()
        write_mbpp_public_tests()
        patch_scensemble_labels()
        patch_prompt_definition_rule()
        patch_retry_budget()
        patch_code_execution()
        patch_indented_code()
        patch_namespace_override()
        verify_syntax()

    print("\n" + "=" * 60)
    if problems:
        print(f"AFlow shim: {len(problems)} problem(s)")
        for item in problems:
            print("  -", item)
        sys.exit(1)
    print("AFlow shim OK")


if __name__ == "__main__":
    main()
